name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # permite usar token customizado para push

    - name: Build and test with Maven
      run: mvn clean verify

    - name: Prepare JaCoCo report files for publishing
      run: |
        if [ ! -d target/site/jacoco ]; then
          echo "Relat처rio JaCoCo n찾o encontrado. Abortando."
          exit 1
        fi
        # Remove tudo, exceto a pasta .github (pra evitar apagar workflow)
        git rm -rf . || true
        git clean -fdx

        # Copia relat처rio para raiz da branch
        cp -r target/site/jacoco/* .

    - name: Commit and push JaCoCo report to GitHub Pages branch
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # Cria ou troca para a branch relatorio-jacoco
        git checkout -B relatorio-jacoco

        git add .
        git commit -m "Publica relat처rio JaCoCo no GitHub Pages [ci skip]" || echo "Nothing to commit"

        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/rodolfooliveira-Professor/pratica-java-jacoco.git

        git push origin relatorio-jacoco --force
