name: CI com JaCoCo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Rodar testes e gerar relatório JaCoCo
      run: mvn clean test jacoco:report

    - name: Copiar relatório JaCoCo para docs/
      run: |
        rm -rf docs
        mkdir docs
        cp -r target/site/jacoco/* docs/

    - name: Commit automático do relatório
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add docs
        git commit -m "Atualiza relatório JaCoCo [ci skip]" || echo "Sem mudanças para commitar"
        git push origin HEAD
