name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and test with Maven
      run: mvn clean test jacoco:report

    - name: Commit and push JaCoCo report
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # Checkout ou cria a branch relatorio-jacoco localmente
        git checkout relatorio-jacoco || git checkout -b relatorio-jacoco

        # Adiciona e comita mudanças no relatório
        git add target/site/jacoco/
        git commit -m "Atualiza relatório JaCoCo [ci skip]" || echo "Nothing to commit"

        # Configura o remote com token para push autenticado
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/rodolfooliveira-Professor/avaliacao-java-jacoco.git

        # Busca últimas mudanças do remoto e rebaseia para evitar rejeição
        git fetch origin relatorio-jacoco
        git reset --hard origin/relatorio-jacoco

        # Push na branch relatorio-jacoco
        git push origin relatorio-jacoco
