name: CI com JaCoCo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar o Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Rodar testes e gerar relatório do JaCoCo
      run: mvn clean test jacoco:report

    - name: Copiar relatório do JaCoCo para pasta docs/
      run: |
        rm -rf docs
        mkdir docs
        cp -r target/site/jacoco/* docs/

    - name: Commit automático do relatório
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add docs
        git commit -m "Atualiza relatório JaCoCo [ci skip]" || echo "Sem mudanças para commitar"
        git push
