name: CI com JaCoCo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do reposit贸rio
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Rodar testes e gerar relat贸rio JaCoCo
      run: mvn clean test jacoco:report

    - name: Copiar relat贸rio JaCoCo para docs/
      run: |
        rm -rf docs
        mkdir docs
        cp -r target/site/jacoco/* docs/

    - name: Push JaCoCo report to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/rodolfooliveira-Professor/avaliacao-java-jacoco.git
        git add docs
        git commit -m "Atualiza relat贸rio JaCoCo [ci skip]" || echo "Nada para commitar"
        git push origin main
