name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'               # aspas curvas simples
        distribution: 'temurin'         # aspas curvas simples

    - name: Build and test with Maven
      run: mvn clean test jacoco:report

    - name: Commit and push JaCoCo report
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name “github-actions”     # aspas curvas duplas
        git config user.email “github-actions@github.com”
        git add target/site/jacoco/
        git commit -m “Atualiza relatório JaCoCo [ci skip]” || echo “Nothing to commit”
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/SEU_USUARIO/SEU_REPOSITORIO.git
        git push origin main
